services:
  lva-tldr:
    image: ghcr.io/martinreisinger/lva-tldr:latest
    container_name: lva-tldr
    restart: unless-stopped
    environment:
      NODE_ENV: production
      TZ: Europe/Vienna
    ports:
      - "127.0.0.1:3009:3000"
